-- Query to identify tickets exceeding SLA first response time
SELECT 
    t.TICKET_NUMBER,
    t.SUBJECT,
    t.STATUS,
    t.CREATED_AT,
    t.FIRST_RESPONSE_AT,
    u.NAME as USER_NAME,
    u.EMAIL as USER_EMAIL,
    u.SERVICE_LEVEL,
    u.CUSTOMER_MANAGER,
    TIMESTAMPDIFF(HOUR, t.CREATED_AT, CURRENT_TIMESTAMP()) as HOURS_SINCE_CREATED,
    CASE 
        WHEN u.SERVICE_LEVEL = 'basic' THEN 72
        WHEN u.SERVICE_LEVEL = 'pro' THEN 36
        WHEN u.SERVICE_LEVEL = 'max' THEN 24
    END as SLA_HOURS,
    CASE 
        WHEN u.SERVICE_LEVEL = 'basic' THEN 72
        WHEN u.SERVICE_LEVEL = 'pro' THEN 36
        WHEN u.SERVICE_LEVEL = 'max' THEN 18
    END as SECOND_REPLY_HOURS
FROM SUPPORT_TICKETS t
JOIN USERS u ON t.USER_ID = u.ID
WHERE t.FIRST_RESPONSE_AT IS NULL
  AND (
    (u.SERVICE_LEVEL = 'basic' AND TIMESTAMPDIFF(HOUR, t.CREATED_AT, CURRENT_TIMESTAMP()) > 72)
    OR (u.SERVICE_LEVEL = 'pro' AND TIMESTAMPDIFF(HOUR, t.CREATED_AT, CURRENT_TIMESTAMP()) > 36)
    OR (u.SERVICE_LEVEL = 'max' AND TIMESTAMPDIFF(HOUR, t.CREATED_AT, CURRENT_TIMESTAMP()) > 24)
  )
ORDER BY 
    CASE u.SERVICE_LEVEL
        WHEN 'max' THEN 1
        WHEN 'pro' THEN 2
        WHEN 'basic' THEN 3
    END,
    t.CREATED_AT ASC;
